In [1]:
import torch
from torch import Tensor
from torch.nn import functional as F

In [2]:
torch.set_printoptions(precision=16, sci_mode=False)

In [11]:
G_game = 0.001
G_game_tensor = torch.Tensor([G_game])

In [12]:
import filepath
from util.math import one,safe_reciprocal

In [14]:
dist_sq_rcpr = Tensor([[0.0000, 0.0124],
        [0.0124, 0.0000]])
mass = Tensor([1000000., 1000000.])

In [3]:
d1 = torch.Tensor([8.7252, 0.530555])
d2 = torch.Tensor([-8.72161, -0.586524])
torch.norm(d1), torch.norm(d2)

(tensor(8.7413158416748047), tensor(8.7413091659545898))

In [6]:
dist_sq_rcpr

tensor([[0.0000, 0.0124],
        [0.0124, 0.0000]])

In [15]:
gravity_scalar = torch.einsum(
            "o, n, mn, m -> mn",
            G_game_tensor,
            mass, dist_sq_rcpr, mass
        )

In [16]:
gravity_scalar

tensor([[       0., 12400002.],
        [12400002.,        0.]])

In [17]:
1/80.7210540771484375

0.01238834169638393

In [22]:
torch.reciprocal(Tensor([80.7210540771484375]))

tensor([0.0123883420601487])