In [37]:
from panda3d.core import Geom, GeomVertexData, GeomVertexFormat
import numpy as np

# 创建带位置和颜色的自定义顶点格式
format = GeomVertexFormat.get_v3c4()  # v3c4 表示 3D 位置 + 4 分量颜色
vertex_data = GeomVertexData("vertices", format, Geom.UHStatic)
position_array = vertex_data.modify_array(0)  # 获取第一个数组（位置数据）
position_handle = position_array.modify_handle()
_ = (position_handle.get_data())


# 创建位置数据，假设是 Nx3 的 NumPy 数组
positions = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
], dtype=np.float32)

# 将 NumPy 数组直接写入到 GeomVertexData 的位置流
position_array = vertex_data.modify_array(0)  # 获取第一个数组（位置数据）
position_handle = position_array.modify_handle()
position_handle.set_data(positions.tobytes())  # 将位置数据写入

# 此时颜色数据未设置，保持为空或为默认值


In [38]:
positions.shape[0]

3

In [39]:
num_vertices = vertex_data.get_num_rows()
num_vertices

2

In [40]:
help(vertex_data.modify_array)

Help on built-in function modify_array:

modify_array(...) method of panda3d.core.GeomVertexData instance
    C++ Interface:
    modify_array(const GeomVertexData self, int i)
    
    /**
     * Returns a modifiable pointer to the indicated vertex array, so that
     * application code may directly manipulate the data.  You should avoid
     * changing the length of this array, since all of the arrays should be kept
     * in sync--use set_num_rows() instead.
     *
     * Don't call this in a downstream thread unless you don't mind it blowing
     * away other changes you might have recently made in an upstream thread.
     */



In [41]:
form = position_array.array_format
type(form)

panda3d.core.GeomVertexArrayFormat

In [42]:
from panda3d.core import GeomVertexArrayFormat
from typing import Dict, Literal, Tuple
def getFormatField(vformat:GeomVertexArrayFormat) -> Dict[str, Tuple[int,int]]:
    n_col = vformat.get_num_columns()
    field_lengths = [v.get_num_values() for v in vformat.columns]
    field_dict = {
        vformat.columns[i].getName():(sum(field_lengths[:i]), sum(field_lengths[:i+1]))
        for i in range(n_col)
    }
    return field_dict

def getFormatLength(vformat:GeomVertexArrayFormat) -> int:
    return sum([v.get_num_values() for v in vformat.columns])
d = getFormatField(form)

In [47]:
v= (list(form.columns)[0])
c=(list(form.columns)[1])

In [48]:
type(v)

panda3d.core.GeomVertexColumn

In [54]:
v.getTotalBytes()

12

In [55]:
v.getElementStride()

12

In [50]:
c

color(4b)

In [53]:
c.getTotalBytes()

4

In [58]:
c.getComponentBytes()

1

In [57]:
help(c.getTotalBytes)

Help on built-in function getTotalBytes:

getTotalBytes(...) method of panda3d.core.GeomVertexColumn instance
    C++ Interface:
    get_total_bytes(GeomVertexColumn self)
    
    /**
     * Returns the number of bytes used by each element of the column:
     * component_bytes * num_components.
     */



In [56]:
c.getElementStride()

4

In [14]:
# start_column
# end_column
form.columns

<GeomVertexArrayFormat.columns[2] of [ vertex(3f) color(4b) ]>

In [25]:
str(list(d.keys())[0])

'vertex'

In [46]:
v.getName()

vertex

In [76]:
c.get_numeric_type()

0

In [50]:
v.get_num_values()
# help(v.get_element_stride)

3

In [48]:
position_handle.get_data()

b'\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@\x00\x00\xa0@\x00\x00\xc0@\x00\x00\xe0@\x00\x00\x00A\x00\x00\x10A'

In [18]:
_  = np.frombuffer(
    positions.tobytes(),
    np.float32
)
_.resize(3,3)

In [19]:
_

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [3]:
from panda3d.core import Geom, GeomVertexData, GeomVertexFormat, GeomVertexWriter, GeomVertexReader
import numpy as np
v3c4 = GeomVertexFormat.get_v3c4() 

In [ ]:


# 创建带位置和颜色的自定义顶点格式
 # v3c4 表示 3D 位置 + 4 分量颜色
vertex_data = GeomVertexData("vertices", format, Geom.UHStatic)
position_array = vertex_data.modify_array(0)  # 获取第一个数组（位置数据）
position_handle = position_array.modify_handle()
_ = (position_handle.get_data())


# 创建位置数据，假设是 Nx3 的 NumPy 数组
positions = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
], dtype=np.float32)

# 将 NumPy 数组直接写入到 GeomVertexData 的位置流
position_array = vertex_data.modify_array(0)  # 获取第一个数组（位置数据）
position_handle = position_array.modify_handle()
position_handle.set_data(positions.tobytes())  # 将位置数据写入

# 此时颜色数据未设置，保持为空或为默认值


In [4]:
vertex_data_manual = GeomVertexData('manual', v3c4, Geom.UHStatic)
vertex_writer = GeomVertexWriter(vertex_data_manual, 'vertex')
positions = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
], dtype=np.float32)
for i in range(3):
    
    vertex_writer.add_data3f(*positions[i])
    

In [5]:
vmarr = vertex_data_manual.modify_array(0)

In [6]:
vmarr

3 rows: [ vertex(3f) color(4b) ]

In [7]:
vmh = vmarr.modifyHandle()

In [9]:
vmb = vmh.getData()

In [10]:
vmnp = np.frombuffer(vmb, np.float32)

In [12]:
vmnp.shape

(12,)

In [13]:
vmnp.resize(3,4)
vmnp

array([[ 1.,  2.,  3., nan],
       [ 4.,  5.,  6., nan],
       [ 7.,  8.,  9., nan]], dtype=float32)

In [66]:
colors = np.array([
    [1.0, 0.1, 0.0, 1.0],  # Red
    [0.0, 1.0, 0.0, 1.0],  # Green
    [0.0, 0.0, 1.0, 1.0]   # Blue
], dtype=np.float32)
vertex_data_manual_c = GeomVertexData('manual', v3c4, Geom.UHStatic)
vertex_writer = GeomVertexWriter(vertex_data_manual_c, 'color')
for i in range(3):
    
    vertex_writer.add_data4f(*colors[i])
vmcarr = vertex_data_manual_c.modify_array(0)
vmch = vmcarr.modifyHandle()
vmcb = vmch.getData()
vmcnp = np.frombuffer(vmcb, np.uint8)

In [67]:
vmcnp.shape

(48,)

In [68]:
vmcnp.resize(3,16)
vmcnp

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 255,
         25,   0, 255],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        255,   0, 255],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 255, 255]], dtype=uint8)

In [73]:
help(vertex_writer.add_data1i)

Help on built-in function add_data1i:

add_data1i(...) method of panda3d.core.GeomVertexWriter instance
    C++ Interface:
    add_data1i(const GeomVertexWriter self, int data)
    
    /**
     * Sets the write row to a particular 1-component value, and advances the
     * write row.
     *
     * If the write row advances past the end of data, implicitly adds a new row
     * to the data.
     */



In [ ]:
colors = np.array([
    [1.0, 0.0, 0.0, 1.0],  # Red
    [0.0, 1.0, 0.0, 1.0],  # Green
    [0.0, 0.0, 1.0, 1.0]   # Blue
], dtype=np.float32)
vertex_data_manual_c = GeomVertexData('manual', v3c4, Geom.UHStatic)
vertex_writer = GeomVertexWriter(vertex_data_manual_c, 'vertex')
for i in range(3):
    
    vertex_writer.add_data4f(*colors[i])
vmcarr = vertex_data_manual_c.modify_array(0)
vmch = vmcarr.modifyHandle()
vmcb = vmch.getData()
vmcnp = np.frombuffer(vmcb, np.float32)

In [77]:
sizeof(int)

NameError: name 'sizeof' is not defined

In [79]:
np.float32.itemsize()

TypeError: 'getset_descriptor' object is not callable

In [80]:
np.dtype(np.float32).itemsize

4

In [81]:
np.dtype(np.uint8).itemsize

1